
apiVersion: newrelic.com/v1alpha2
kind: Instrumentation
metadata:
  name: newrelic-python-instrumentation
  namespace: newrelic
spec:
  agent:
    # Values supported: dotnet, java, nodejs, python, ruby, php
    language: python

    # Values supported: newrelic-java-init:latest, newrelic-dotnet-init:latest, newrelic-node-init:latest, newrelic-python-init:latest, newrelic-ruby-init:latest, newrelic-php-init:latest, newrelic-php-init:musl
    image: newrelic/newrelic-python-init:latest
    env:
    # Example overriding the appName configuration
    # - name: NEW_RELIC_APP_NAME
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.labels['app.kubernetes.io/name']

  # Select a namespace with a specific name by using "kubernetes.io/metadata.name" label
  namespaceLabelSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["default"]

 # Select pods containing a specific label and value
  podLabelSelector:
    matchExpressions:
      - key: "app"
        operator: "In"
        values: ["ai-chatbot"]
---
apiVersion: newrelic.com/v1alpha2
kind: Instrumentation
metadata:
  name: newrelic-dotnet-instrumentation
  namespace: newrelic
spec:
  agent:
    # Values supported: dotnet, java, nodejs, python, ruby, php
    language: dotnet

    # Values supported: newrelic-java-init:latest, newrelic-dotnet-init:latest, newrelic-node-init:latest, newrelic-python-init:latest, newrelic-ruby-init:latest, newrelic-php-init:latest, newrelic-php-init:musl
    image: newrelic/newrelic-dotnet-init:latest
    env:
    # Example overriding the appName configuration
    # - name: NEW_RELIC_APP_NAME
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.labels['app.kubernetes.io/name']

  # Select a namespace with a specific name by using "kubernetes.io/metadata.name" label
  namespaceLabelSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["default"]

 # Select pods containing a specific label and value
  podLabelSelector:
    matchExpressions:
      - key: "app"
        operator: "In"
        values: ["backend-api"]
---
apiVersion: newrelic.com/v1alpha2
kind: Instrumentation
metadata:
  name: newrelic-nodejs-instrumentation
  namespace: newrelic
spec:
  agent:
    # Values supported: dotnet, java, nodejs, python, ruby, php
    language: nodejs

    # Values supported: newrelic-java-init:latest, newrelic-dotnet-init:latest, newrelic-node-init:latest, newrelic-python-init:latest, newrelic-ruby-init:latest, newrelic-php-init:latest, newrelic-php-init:musl
    image: newrelic/newrelic-node-init:latest
    env:
    # Example overriding the appName configuration
    # - name: NEW_RELIC_APP_NAME
    #   valueFrom:
    #     fieldRef:
    #       fieldPath: metadata.labels['app.kubernetes.io/name']

  # Select a namespace with a specific name by using "kubernetes.io/metadata.name" label
  namespaceLabelSelector:
    matchExpressions:
      - key: "kubernetes.io/metadata.name"
        operator: "In"
        values: ["default"]

 # Select pods containing a specific label and value
  podLabelSelector:
    matchExpressions:
      - key: "app"
        operator: "In"
        values: ["frontend"]
