---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: default
type: Opaque
data:
  openai-api-key: c2stcHJvai1ubnQyVVc1YnBzY2FvVkRHeGI3RFFHUHpuaEpRMnB0SkVRSmJSNWQ3YTYtYzAzXzlHVkNKVEJtM1NmWVZtSlVLbzV5N1pzbHNqa1QzQmxia0ZKZXEwUUlFem5mVVllTkwxRDR3eUNTMldMYzZXNER5NFJrYVMyRlpIN1lYTXFQZTd0TFhBRzdXRUVlR082dkIxRlZ3bk1EUGVmWUE=
---
apiVersion: v1
kind: Secret
metadata:
  name: newrelic-license-key
type: Opaque
data:
  NEW_RELIC_LICENSE_KEY: MGNmNWM1NjEwMzJiY2UwNjc2NWNkM2VlN2NiMWMwMTRGRkZGTlJBTA==